# Generated by Django 3.2 on 2023-04-11 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book', to='library.book', verbose_name='book'),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='account.customuser', verbose_name='student'),
        ),
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_Staff_name', to='account.customuser', verbose_name='staff'),
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_Author_name', to='account.customuser', verbose_name='author'),
        ),
    ]
