# Generated by Django 3.2 on 2023-04-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], default='active', max_length=100, verbose_name='status'),
        ),
    ]
